backend:
  name: github
  repo: <% GITHUB_REPOSITORY %> # Gulp will replace this with your GitHub repository
  branch: master # Branch to update (master by default)

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "case-studies"
    label: "Case Studies"
    folder: "site/content/case-studies"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Services", name: "services", widget: "string", required: false}
      - {label: Showcase, name: showcase, widget: object, fields: [
          {label: Heading, name: heading, widget: string},
          {label: Images, name: images, widget: list, fields: [{label: Image, name: image, widget: image},
          {label: Text, name: text, widget: text}]}
        ]}

